[theme]


 primaryColor="#3872fb"
 backgroundColor="#0e1117"
 secondaryBackgroundColor="#31333F"
 textColor="#fafafa"
 font="sans serif"

[server]

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 110

[client]

# Whether to enable st.cache.
# Default: true
caching = true
